ab_cu_t/urls.py
from django.urls import path
from . import views

app_name = 'ab_cu_t'

urlpatterns = [
    path('about/', views.about_page, name='about_page'),
    path('contact/', views.contact_page, name='contact_page'),
    path('location/', views.location_page, name='location_page'),
    path('terms/', views.terms_page, name='terms_page'),
    path('redirect_to_main/', views.redirect_to_main, name='redirect_to_main'),
]

contact/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name='contact'

urlpatterns = [
    path('contact/', views.contact, name='contact'),
]

form/urls.py
from django.urls import path
from .views import *

app_name = 'form'

urlpatterns = [
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', logout_user, name='logout'),
    path('register/', RegisterUser.as_view(), name='register'),
]

hosting/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.main, name='main'),
    path('admin/', admin.site.urls),
    path('servers/', include('servers.urls')),
    path('ab-cu-t/', include('ab_cu_t.urls')),
    path('payment/', include('payment.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('form/', include('form.urls')),
    path('contact/', include('contact.urls'))


]

payment/urls.py
from django.urls import path
from . import views

app_name = "payment"

urlpatterns = [

    path('payment/', views.payment_page, name='payment_page'),  # Це ваша сторінка у додатку payment
    path('payment/', views.success_page, name='success_page'),  # URL для сторінки успішної оплати
]

servers/urls.py
from django.urls import path
from . import views

app_name = "servers"

urlpatterns = [
    path('dedicated/', views.dedicated_page, name='dedicated_page'),
    path('shared/', views.shared_page, name='shared_page'),
    path('virtual/', views.virtual_page, name='virtual_page'),
    path('redirect_to_main/', views.redirect_to_main, name='redirect_to_main'),
    path('redirect_to_login/', views.redirect_to_login, name='redirect_to_login'),
    path('payment/', views.payment_page, name='payment_page'),
]

ab_cu_t/models.py
from django.db import models

# Create your models here.

contact/models.py
from django.db import models

# Create your models here.

form/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

hosting/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

servers/models.py
from django.db import models

# Create your models here.

contact/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField(label='Full Name', max_length=100)
    email = forms.EmailField(label='Email Address', max_length=100)
    message = forms.CharField(label='Message', widget=forms.Textarea)

form/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

from .models import *


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    email = forms.EmailField(label='Email', widget=forms.EmailInput(attrs={'class': 'form-input'}))
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    password2 = forms.CharField(label='Повтор пароля', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

hosting/forms.py
from django.contrib.auth.forms import UserCreationForm

ab_cu_t/views.py
from django.shortcuts import render, redirect

def redirect_to_main(request):
    return redirect('main')

def about_page(request):
    return render(request, 'ab_cu_t/about.html')

def contact_page(request):
    return render(request, 'ab_cu_t/contact.html')

def location_page(request):
    return render(request, 'ab_cu_t/locations.html')

def terms_page(request):
    return render(request, 'ab_cu_t/terms.html')

contact/views.py
from django.core.mail import send_mail
from django.shortcuts import render, redirect
from django.conf import settings
from .forms import ContactForm


def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            message = form.cleaned_data['message']

            # Відправте лист на електронну пошту
            send_mail(
                'Повідомлення від користувача',
                f'Ім\'я: {name}\nЕлектронна адреса: {email}\nПовідомлення: {message}',
                settings.DEFAULT_FROM_EMAIL,
                ['pavlokolodiy824@gmail.com'],  # Замініть це на свою адресу електронної пошти
                fail_silently=False,
            )

            return redirect('contact:contact')  # Змініть на свій URL підтвердження
    else:
        form = ContactForm()

    return render(request, 'contact/contact.html', {'form': form})

def send_message(name, email, message):
    pass

form/views.py
from django.contrib.auth import logout, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
from django.core.paginator import Paginator
from django.http import HttpResponse, HttpResponseNotFound, Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin

from .forms import *
from .models import *


class RegisterUser(CreateView):
    form_class = RegisterUserForm
    template_name = 'form/register.html'
    success_url = reverse_lazy('login')

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('main')


class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'form/login.html'

    def get_success_url(self):
        return reverse_lazy('main')


def logout_user(request):
    logout(request)
    return redirect('main')

hosting/views.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.views import LoginView
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView


def main(request):
    return render(request, 'stg/index.html')

payment/views.py
# views.py

from django.shortcuts import render, redirect


def payment_page(request):
    price = request.GET.get('price', '')  # Отримати ціну з параметру URL
    return render(request, 'payment/payment_method.html', {'price': price})


def success_page(request):
    return render(request, 'payment/success_page.html')

servers/views.py
from django.shortcuts import render, redirect

def redirect_to_main(request):
    return redirect('main')

def dedicated_page(request):
    return render(request, 'servers/dedicated.html')

def shared_page(request):
    return render(request, 'servers/shared.html')

def virtual_page(request):
    return render(request, 'servers/virtual.html')

def redirect_to_login(request):
    return render(request, '')

def payment_page(request):
    price = request.GET.get('price', '')  # Отримати ціну з параметру URL
    return render(request, 'payment/payment_method.html', {'price': price})

contact/templates/contact/success_url.html
<!DOCTYPE html>

<html>
    <body>
        <h1>Contact</h1>
    JKSDNJKSDGDSK;
    </body>
</html>

form/templates/form/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<title>Rackhost Hosting & Business Theme</title>
		<meta charset="utf-8" />
		<meta content="rackhost, server, theme" name="keywords" />
		<meta content="Rackhost hosting and business theme." name="description" />
		<link rel="shortcut icon" href="favicon.ico" />
		<link rel="icon" href="favicon.ico" type="image/x-icon" />
		<link href="{% static 'css/rackhost.css' %}" rel="stylesheet" type="text/css" />
		<script src="{% static 'js/jquery-1.7.2.min.js' %}" type="text/javascript"></script>
		<script src="{% static 'js/rackhost.js' %}" type="text/javascript"></script>
	</head>
	<body>
		<div class="siteWrapper">
			<div class="siteHeaderShadow">
			</div>
			<div class="siteHeader">
				<div class="center">
					<a class="logo" href="{% url 'servers:redirect_to_main' %}"></a>
					<ul class="navigation">
						<li>
							<a href="shared.html"><strong>Shared</strong> Hosting<br /><span>cPanel powered</span></a>
						</li>
						<li>
							<a class="dropdown" href="virtual.html"><strong>Virtual</strong> Servers<br /><span>OpenVZ or Xen</span></a>
						</li>
						<li>
							<a href="dedicated.html"><strong>Dedicated</strong> Servers<br /><span>cPanel or Unmanaged</span></a>
						</li>
						<li>
							<a class="dropdown" href="about.html"><strong>About</strong> Rackhost<br /><span>Who We Are</span></a>
						</li>
						<li>
							<a href="contact.html"><strong>Contact</strong> Us<br /><span>Custom Quotes</span></a>
						</li>
					</ul>
				</div>
			</div>
			<div class="contentHeader">
				<div class="center">
					<h1>Client <span>Login</span></h1>
					<ul>
						<li><a class="iconSmallPhone" href="contact.html"><strong>USA</strong> 123.456.7891</a></li>
						<li><a class="iconSmallChat" href="contact.html"><strong>Live</strong> Chat</a></li>
						<li><a class="iconSmallEmail" href="contact.html"><strong>Email</strong> Support</a></li>
						<li><a class="iconSmallClient" href="login.html"><strong>Client</strong> Login</a></li>
					</ul>
				</div>
			</div>
			<div class="contentWrapper">
				<div class="outerShadow">
				</div>
				<div class="innerShadow">
				</div>
				<div class="center clearfix">
					<div class="clearfix">
					</div>
					<form class="loginForm" method="post">
                        {% csrf_token %}
						<div class="column">
							<label for="email">Email Address</label>
							<input id="email" name="username" type="text" />
						</div>
						<div class="column">
							<label for="password">Password</label>
							<input id="password" name="password" type="password" />
						</div>
						<div class="column checkbox">
							<input id="save" name="save" type="checkbox" /><label for="save">Remember me on this computer</label>
						</div>
                        {{ form.errors }}
						<button class="colorButton">Login</button>
						<div class="help">
							<a href="contact.html">Forgot your password?</a>
                            <a href="{% url 'form:register' %}">Sign in</a>
						</div>
					</form>
				</div>
			</div>
			<div class="twitterWidget">
				<div class="center">
					<a class="profileLink" href=""></a><p>Loading<span>Retrieving latest tweet...</span></p>
				</div>
			</div>
			<div class="siteFooter">
				<div class="center clearfix">
					<div class="column tiny">
						<h5>Main <span>Navigation</span></h5>
						<ul class="columnNavigation">
							<li><a href="shared.html"><strong>Shared</strong> Hosting</a></li>
							<li><a href="virtual.html"><strong>Virtual</strong> Servers</a></li>
							<li><a href="dedicated.html"><strong>Dedicated</strong> Servers</a></li>
							<li><a href="about.html"><strong>About</strong> Rackhost</a></li>
							<li><a href="contact.html"><strong>Contact</strong> Us</a></li>
						</ul>
					</div>
					<div class="column tiny">
						<h5>Additional <span>Information</span></h5>
						<ul class="columnNavigation">
							<li><a href="terms.html"><strong>Site</strong> Map</a></li>
							<li><a href="terms.html"><strong>Terms</strong> of Service</a></li>
							<li><a href="terms.html"><strong>Privacy</strong> Policy</a></li>
							<li><a href="terms.html"><strong>DMCA</strong> Policy</a></li>
						</ul>
					</div>
					<div class="column tiny">
						<h5>Support <span>Center</span></h5>
						<ul class="columnNavigation">
							<li><a class="iconSmallPhone" href="contact.html"><strong>USA</strong> 123.456.7891</a></li>
							<li><a class="iconSmallChat" href="contact.html"><strong>Live</strong> Chat</a></li>
							<li><a class="iconSmallEmail" href="contact.html"><strong>Email</strong> Support</a></li>
							<li><a class="iconSmallClient" href="login.html"><strong>Client</strong> Login</a></li>
						</ul>
					</div>
					<div class="column tiny last">
						<h5>About <span>Rackhost</span></h5>
						<p class="text">Rackhost provides enterprise hosting and server services at an amazing price. Don't see something that suits your needs? <a href="contact.html">Get a free custom quote</a> from one of our hosting experts.</p>
					</div>
				</div>
			</div>
			<div class="siteFooterBar">
				<div class="center">
					<a class="backToTop" href="#">Back to Top</a><p>Follow us on <a href="#">Twitter</a>, <a href="#">Facebook</a> or <a href="#">LinkedIn</a> to receive updates regarding network issues, discounts and more.<br />2012 &copy; Rackhost. All rights reserved. Design by <a href="http://serifly.com">Serifly</a>
				</div>
			</div>
		</div>
	</body>
</html>

payment/templates/payment/success_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    Вітаємо оплата пройшла успішно
</body>
</html>

servers/templates/servers/dedicated.html
{% load static %}
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<title>Rackhost Hosting & Business Theme</title>
		<meta charset="utf-8" />
		<meta content="rackhost, server, theme" name="keywords" />
		<meta content="Rackhost hosting and business theme." name="description" />
		<link rel="shortcut icon" href="favicon.ico" />
		<link rel="icon" href="favicon.ico" type="image/x-icon" />
		<link href="{% static 'css/rackhost.css' %}" rel="stylesheet" type="text/css" />
		<script src="{% static 'js/jquery-1.7.2.min.js' %}" type="text/javascript"></script>
		<script src="{% static 'js/rackhost.js' %}" type="text/javascript"></script>
	</head>
	<body>
		<div class="siteWrapper">
			<div class="siteHeaderShadow">
			</div>
			<div class="siteHeader">
				<div class="center">
					<a class="logo" href="{% url 'servers:redirect_to_main' %}"></a>
					<ul class="navigation">
                        <li>
							<a href="{% url 'servers:shared_page' %}"><strong>Shared</strong> Hosting<br /><span>cPanel powered</span></a>
						</li>
						<li>
							<a class="dropdown" href="{% url 'servers:virtual_page' %}"><strong>Virtual</strong> Servers<br /><span>OpenVZ or Xen</span></a>
						</li>
						<li>
							<a href="{% url 'servers:dedicated_page' %}"><strong>Dedicated</strong> Servers<br /><span>cPanel or Unmanaged</span></a>
						</li>
						<li>
							<a class="dropdown" href="{% url 'ab_cu_t:about_page' %}"><strong>About</strong> Rackhost<br /><span>Who We Are</span></a>
						</li>
						<li>
							<a href="{% url 'ab_cu_t:contact_page' %}"><strong>Contact</strong> Us<br /><span>Custom Quotes</span></a>
						</li>
					</ul>
				</div>
			</div>
			<div class="contentHeader">
				<div class="center">
					<h1>Dedicated <span>Servers</span></h1>
						<ul>
							<li><a class="iconSmallPhone" href="{% url 'ab_cu_t:contact_page' %}"><strong>USA</strong> 123.456.7891</a></li>
							<li><a class="iconSmallChat" href="{% url 'ab_cu_t:contact_page' %}"><strong>Live</strong> Chat</a></li>
							<li><a class="iconSmallEmail" href="{% url 'ab_cu_t:contact_page' %}"><strong>Email</strong> Support</a></li>
{#							<li><a class="iconSmallClient" href="{% url 'form:login_page' %}"><strong>Client</strong> Login</a></li>#}
                            {% if request.user.is_authenticated %}
                            <li><a class="iconSmallClient ">{{ user.username }}</a></li>
                            <li><a href="{% url 'form:logout' %}">Вийти</a></li>
                            {% else %}
                            <li><a class="iconSmallClient" href="{% url 'form:login' %}">Login </a></li>
                            <li><a class="iconSmallClient" href="{% url 'form:register' %}">Register</a></li>
                            {% endif %}
						</ul>
				</div>
			</div>
			<div class="contentWrapper">
				<div class="outerShadow">
				</div>
				<div class="innerShadow">
				</div>
				<div class="center clearfix">
					<div class="clearfix">
					</div>
					<p class="hostingHeader dedicated">Our shared hosting nodes are built with enterprise hardware and never oversold. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
					<div class="hostingPlans clearfix">
						<div class="column medium">
							<h1>Dedicated Entry<br /><span>Medium Computing Power</span></h1>
							<ul class="keyFeatures">
								<li><strong>8 GB RAM</strong> 4x 2 GB DDR3</li>
								<li><strong>Xeon E3-1230</strong> 4x 2,4 GHz</li>
								<li><strong>2 TB RAID 1</strong> 2x 2 TB SATA</li>
								<li><strong>10 TB</strong> Premium Traffic</li>
							</ul>
							<ul class="additionalFeatures">
								<li>No Setup Fee</li>
								<li>1000 MBit Port</li>
								<li>Enterprise Supermicro Hardware</li>
								<li>99.999% Uptime Guarantee</li>
							</ul>
							<div class="price">
								<strong>$199</strong><br /><span>monthly or $2200 yearly</span>
							</div>
							<a class="colorButton" href="{% url 'servers:payment_page' %}?price=199"><span class="pointer">Order now</span></a>
						</div>
						<div class="column medium">
							<h1>Dedicated Highend<br /><span>High Computing Power</span></h1>
							<ul class="keyFeatures">
								<li><strong>24 GB RAM</strong> 8x 4 GB ECC</li>
								<li><strong>Dual Xeon E5-2620</strong> 8x 2,8 GHz</li>
								<li><strong>600 GB RAID 10</strong> 4x 300 GB SAS 15000 RPM</li>
								<li><strong>20 TB</strong> Premium Traffic</li>
							</ul>
							<ul class="additionalFeatures">
								<li>No Setup Fee</li>
								<li>1000 MBit Port</li>
								<li>Enterprise Supermicro Hardware</li>
								<li>99.999% Uptime Guarantee</li>
							</ul>
							<div class="price">
								<strong>$399</strong><br /><span>monthly or $4600 yearly</span>
							</div>
							<a class="colorButton" href="{% url 'servers:payment_page' %}?price=399"><span class="pointer">Order now</span></a>
						</div>
					</div>
					<div class="contentInfoBox">
						<p>Didn't find what you were looking for? No problem, our engineers will be happy to give you a <a href="{% url 'ab_cu_t:contact_page' %}">custom quote</a>.</p>
					</div>
					<div class="column small">
						<h2 class="iconMediumServer">Enterprise <span>Hardware</span></h2>
						<p class="text">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
					</div>
					<div class="column small">
						<h2 class="iconMediumStats">Usage <span>Statistics</span></h2>
						<p class="text">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
					</div>
					<div class="column small last">
						<h2 class="iconMediumControlPanel">Control <span>Panel</span></h2>
						<p class="text">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do <a href="">eiusmod tempor incididunt</a> ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
					</div>
				</div>
			</div>
			<div class="twitterWidget">
				<div class="center">
					<a class="profileLink"></a><p>Loading<span>Retrieving latest tweet...</span></p>
				</div>
			</div>
			<div class="siteFooter">
				<div class="center clearfix">
					<div class="column tiny">
						<h5>Main <span>Navigation</span></h5>
						<ul class="columnNavigation">
							<li><a href="{% url 'servers:shared_page' %}"><strong>Shared</strong> Hosting</a></li>
							<li><a href="{% url 'servers:virtual_page' %}"><strong>Virtual</strong> Servers</a></li>
							<li><a href="{% url 'servers:dedicated_page' %}"><strong>Dedicated</strong> Servers</a></li>
							<li><a href="{% url 'ab_cu_t:about_page' %}"><strong>About</strong> Rackhost</a></li>
							<li><a href="{% url 'ab_cu_t:contact_page' %}"><strong>Contact</strong> Us</a></li>
						</ul>
					</div>
					<div class="column tiny">
						<h5>Additional <span>Information</span></h5>
						<ul class="columnNavigation">
                            <li><a href="{% url 'ab_cu_t:terms_page' %}"><strong>Site</strong> Map</a></li>
                            <li><a href="{% url 'ab_cu_t:terms_page' %}"><strong>Terms</strong> of Service</a></li>
                            <li><a href="{% url 'ab_cu_t:terms_page' %}"><strong>Privacy</strong> Policy</a></li>
                            <li><a href="{% url 'ab_cu_t:terms_page' %}"><strong>DMCA</strong> Policy</a></li>
						</ul>
					</div>
					<div class="column tiny">
						<h5>Support <span>Center</span></h5>
						<ul class="columnNavigation">
							<li><a class="iconSmallPhone" href="{% url 'ab_cu_t:contact_page' %}"><strong>USA</strong> 123.456.7891</a></li>
							<li><a class="iconSmallChat" href="{% url 'ab_cu_t:contact_page' %}"><strong>Live</strong> Chat</a></li>
							<li><a class="iconSmallEmail" href="{% url 'ab_cu_t:contact_page' %}"><strong>Email</strong> Support</a></li>
{#							<li><a class="iconSmallClient" href="{% url 'form:login_page' %}"><strong>Client</strong> Login</a></li>#}
                            {% if request.user.is_authenticated %}
                            <li><a class="iconSmallClient ">{{ user.username }}</a></li>
                            <li><a href="{% url 'form:logout' %}">Вийти</a></li>
                            {% else %}
                            <li><a class="iconSmallClient" href="{% url 'form:login' %}">Login </a></li>
                            <li><a class="iconSmallClient" href="{% url 'form:register' %}">Register</a></li>
                            {% endif %}
						</ul>
					</div>
					<div class="column tiny last">
						<h5>About <span>Rackhost</span></h5>
						<p class="text">Rackhost provides enterprise hosting and server services at an amazing price. Don't see something that suits your needs? <a href="{% url 'ab_cu_t:contact_page' %}">Get a free custom quote</a> from one of our hosting experts.</p>
					</div>
				</div>
			</div>
			<div class="siteFooterBar">
				<div class="center">
					<a class="backToTop" href="#">Back to Top</a><p>Follow us on <a>Twitter</a>, <a>Facebook</a> or <a>LinkedIn</a> to receive updates regarding network issues, discounts and more.<br />2012 &copy; Rackhost. All rights reserved. Design by <a>Serifly</a>
				</div>
			</div>
		</div>
	</body>
</html>